name: Protect Main Branch PRs

on:
  pull_request:
    branches:
      - main

jobs:
  check_pr_source_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from prod
        if: github.head_ref != 'prod'
        run: |
          echo "Pull requests to main must come from the prod branch."
          exit 1
      - name: Approve PR from prod
        if: github.head_ref == 'prod'
        run: |
          echo "Pull request to main is from prod. Approved."
