name: Run the tests. Check if this can be deployed.

on:
  push:
    branches:
      - dev
  workflow_dispatch: # Allow manual triggering of the workflow

env:
  GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
  CHAT_API_ENDPOINT: ${{ vars.CHAT_API_ENDPOINT }}
  DEFAULT_CHAT_LOCATION: ${{ vars.DEFAULT_CHAT_LOCATION }}

jobs:
  run_build_and_tests_via_reusable_workflow: # Renamed job for clarity
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      node-version: '18'
      expo-working-directory: 'ExpoGallery'
      output-path: 'dist' # Standard output path, though not used here
      cache-dependency-path: 'ExpoGallery/package-lock.json'
    # If the reusable workflow needed secrets for the build/test process:
    # secrets:
    #   SOME_SECRET: ${{ secrets.SOME_SECRET_IN_CALLER }}
